### PR TITLE
s/tumbor/thumbor/

### PR DESCRIPTION
**Pull request by kylemarsh**
Fix typo added when moving from if-else to switch.

### CODE REVIEW

**Comment by kylemarsh** [comment]
Aside from this change, does anyone have a sample thumbor config file for using with 50mm? I haven't found any documentation for it yet (maybe I'm just missing it?) and I haven't been able to make it work yet: the URLs 50mm generates seem to be invalid (at least given the stock configuration). For instance:

`https://localhost:8888/GOOP/800x0/smart/prefix/to/photo.jpg`
as opposed to 
`http://localhost:8888/GOOP/800x0/smart/http://bucket.objectstore.com/prefix/to/photo.jpg`

(also, it's generating HTTPS links by default and I'm not sure if there's a way to disable that or if I need to actually get a legitimate certificate for my thumbor service)

Any advice? Since the individual image pages exist now, I've got a change to the CSS to make the album page more of a set of thumbnails, but I want to make sure it works with resizing services before I submit a pull request for it. In deference to the desire for simplicity, I also might see about putting something into the configuration to specify whether an album page shows thumbnails or full-sized images. For the moment you can get a preview of the responsive album page here: http://photos.kmarsh.net/bm2017/

**Comment by arahayrabedian** [comment]
Hi @kylemarsh , thanks for catching that typo!

I'll have to get back to you on your questions - wrote the thumbor implementation a while back and my morning just started.

I can't remember why HTTPS was enforced, but I'll look in to if an override is feasible without compromising anything, that said, huge fan of let's encrypt for free certs (plus caddy web server to make life even easier!)

**Comment by arahayrabedian** [comment]
@kylemarsh can you do me a favour and open an issue with basically the same text pasted in so I can get back to you later without making a mess here?

**Comment by kylemarsh** [comment]
Sure thing! Thanks for the speedy response.

**Comment by kylemarsh** [comment]
Done. I actually split it into two issues; #19 is about thumbor and #20 is seeding a discussion about possibly incorporating the responsive album overview pages I made for my personal site.

**Pull request merged**
